// <auto-generated />
using System;
using AgiotaDoBem.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgiotaDoBem.Infra.Migrations
{
    [DbContext(typeof(AgiotaDoBemContext))]
    partial class AgiotaDoBemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgiotaDoBem.Domain.Entities.DividasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DiaDaCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeDoEstabelecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("ValorTotalDaCompra")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DividasModel");
                });

            modelBuilder.Entity("AgiotaDoBem.Domain.Entities.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DividasParaPagarId")
                        .HasColumnType("int");

                    b.Property<string>("NomeDoDevedor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DividasParaPagarId");

                    b.ToTable("UsuarioModel");
                });

            modelBuilder.Entity("AgiotaDoBem.Domain.Entities.UsuarioModel", b =>
                {
                    b.HasOne("AgiotaDoBem.Domain.Entities.DividasModel", "DividasParaPagar")
                        .WithMany()
                        .HasForeignKey("DividasParaPagarId");

                    b.Navigation("DividasParaPagar");
                });
#pragma warning restore 612, 618
        }
    }
}
