<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgiotaDoBem.Domain\AgiotaDoBem.Domain.csproj" />
    <ProjectReference Include="..\AgiotaDoBem.Infra\AgiotaDoBem.Infra.csproj" />
  </ItemGroup>

</Project>
